// lib/freightConnectConstants.ts
// Shared constants for Freight Connect UI + API

export const FC_PROVINCES = [
  'Alberta',
  'British Columbia',
  'Manitoba',
  'New Brunswick',
  'Newfoundland and Labrador',
  'Northwest Territories',
  'Nova Scotia',
  'Nunavut',
  'Ontario',
  'Prince Edward Island',
  'Quebec',
  'Saskatchewan',
  'Yukon',
] as const;

export const FC_TARGET_MARKETS = [
  'Australia',
  'Belgium',
  'Brazil',
  'Chile',
  'China',
  'Colombia',
  'Egypt',
  'France',
  'Germany',
  'India',
  'Indonesia',
  'Italy',
  'Japan',
  'Malaysia',
  'Mexico',
  'Morocco',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'Peru',
  'Philippines',
  'Saudi Arabia',
  'Singapore',
  'South Africa',
  'South Korea',
  'Spain',
  'Thailand',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Vietnam',
] as const;

export const FC_HS_CHAPTERS: { code: string; label: string }[] = [
  { code: '01', label: '01 — Live Animals' },
  { code: '02', label: '02 — Meat & Offal' },
  { code: '03', label: '03 — Fish & Seafood' },
  { code: '04', label: '04 — Dairy, Eggs & Honey' },
  { code: '07', label: '07 — Vegetables' },
  { code: '08', label: '08 — Fruit & Nuts' },
  { code: '09', label: '09 — Coffee, Tea & Spices' },
  { code: '10', label: '10 — Cereals (Wheat, Canola, etc.)' },
  { code: '11', label: '11 — Milling Products & Starch' },
  { code: '12', label: '12 — Oil Seeds & Misc. Grains' },
  { code: '15', label: '15 — Animal & Vegetable Fats' },
  { code: '16', label: '16 — Meat & Fish Preparations' },
  { code: '17', label: '17 — Sugar & Confectionery' },
  { code: '18', label: '18 — Cocoa & Chocolate' },
  { code: '19', label: '19 — Cereal Preparations' },
  { code: '20', label: '20 — Vegetable & Fruit Preparations' },
  { code: '21', label: '21 — Food Preparations (Misc.)' },
  { code: '22', label: '22 — Beverages & Spirits' },
  { code: '23', label: '23 — Animal Feed' },
  { code: '27', label: '27 — Mineral Fuels & Oil' },
  { code: '28', label: '28 — Inorganic Chemicals' },
  { code: '29', label: '29 — Organic Chemicals' },
  { code: '30', label: '30 — Pharmaceuticals' },
  { code: '33', label: '33 — Essential Oils & Cosmetics' },
  { code: '34', label: '34 — Soap & Detergents' },
  { code: '35', label: '35 — Proteins & Adhesives' },
  { code: '38', label: '38 — Miscellaneous Chemicals' },
  { code: '39', label: '39 — Plastics & Articles' },
  { code: '40', label: '40 — Rubber & Articles' },
  { code: '44', label: '44 — Wood & Wood Products' },
  { code: '47', label: '47 — Pulp & Paper Waste' },
  { code: '48', label: '48 — Paper & Paperboard' },
  { code: '62', label: '62 — Apparel (Not Knitted)' },
  { code: '73', label: '73 — Iron & Steel Articles' },
  { code: '84', label: '84 — Machinery & Computers' },
  { code: '85', label: '85 — Electrical Equipment' },
  { code: '87', label: '87 — Vehicles & Parts' },
  { code: '90', label: '90 — Optical & Medical Equipment' },
  { code: '94', label: '94 — Furniture & Lighting' },
];

export const FC_SHIPPING_MODES = [
  { value: 'ocean',      label: 'Ocean Freight' },
  { value: 'air',        label: 'Air Freight' },
  { value: 'rail',       label: 'Rail' },
  { value: 'trucking',   label: 'Trucking / Road' },
  { value: 'multimodal', label: 'Multimodal' },
] as const;

export const FC_VOLUME_OPTIONS = [
  { value: '1',    label: '1 shipment / year' },
  { value: '2-5',  label: '2–5 shipments / year' },
  { value: '6-12', label: '6–12 shipments / year' },
  { value: '12+',  label: '12+ shipments / year' },
] as const;

export const BULK_QUOTE_MAX = 3;
